---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: collectorshop-bff
  namespace: cesi-ci-cd-dev
spec:
  encryptedData:
    Bff__ClientSecret: AgC/Yfci8SsHRUlI6zKQrqXQVqUUVDcDA/arnDl1Grbv0lWaW8lgSUd1anaHUoCFBOp87sGwPpj3pPYMu6if+Qca0n0i47dR9ogYstnNtN0jbto1+MhlMaPU5c3fFO+KbRwqgj1XiRkZKXZTawpw9xViP+ahu7/0rIzlIsNoYRp9IC7KevgbMJaE2/RxcbwkxZkQTU8RZT6sOHA2096mu42ysCRFnMUaVwcrEyBx6+cOrr9+PACTy4uEptDcWAyFUgC+o+9r2qESp8JX1UAXD34jS69Cd34vkuLs5fEVTtdB2D2zFeU8dijkius05te3ZRDCWczW54Xg71u013s0UKwhDnut5nXJi0GiJUjSLi8TBX/b7pSe0WeSfys5o06dZs04UuKAUFLNz36OvQNW1qAor2xPw0bTTQR6YVqkDDZZ89P7a6O44kshE3ONdj9U1mALLudA1AgENm22p3YdWqXwynH6J4oSFV+dzHv4p9HRaG2Eo+FzQKqKaWW6m6m2IIWe32k72upelupmbn72hyV5UuiDFT9CvePUUHm33L3b21V+5p3vVgX5eH+nkPWIVnJwx7+eR8fQvUsEz1sg2wI3mDdOBSL/ErEbglTPukE7gOV90NqMEWVhRx7D8P710PnQdlPljifGATGp1QYwhjirc/irsY1JM+opSnKvjo2hAXKTkMcoX4y71fKc2Z/9BlclBXMFBO6iW/QhXpwd5fiaq5eousWAeMLsIGzfA8aTbIjXbR8+h7cib+15ag==
  template:
    metadata:
      name: collectorshop-bff
      namespace: cesi-ci-cd-dev
