apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
data:
  ENV: dev
  ASPNETCORE_ENVIRONMENT: Development
  Bff__Origin: "https://dev.julienforestier.pro"
  IdentityServer__IssuerUri: "https://dev.julienforestier.pro"
