apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: cesi-ci-cd-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCoOdRp1Ry8un6LfYCcHojILGewMFtYbHih9jAtymNBqfdzZx4qWTHJ4cwnqrKnj9A3vE+1E0tZqrhkWwoc/CgrOu12TzjeSR8yHXx43BjJiIrT+qLzXtoMw+IRFgZe8wcvdvGbbiWmFz2OsPDuiK7OH6TwNgEqr/W6bed5pRn+j+l9JluPNsnGt6LLwhoakcqac2kcP64Ez/hFcKFH8mivB9Ko7MD+fmU8mokXZLX8Rpfp8XybTsgba8x+qCd4LwldRu9ItPpSow6jezgFmtI2xDTk5JfxgJOwMnD+eblDXr+WHcpdCtv6gnrmAtgprOQp8s9ioAaM+POGCYdYEKlhEBNGlhJBtESpmAduluz5fHWd+wvv6xjXqy9oAsfRPcdOcya1TvJUOo5YRTYW+tYVPcVuoRTO/d2W9ZCNp7wtgjq01ZlGyv2KkJYlQsGJCFGFcOhyed7/LS6jYQX6Nactg6KGCgUln1tSsK3WnXThYXkK1UBY5beBz9W+DU8n8ihmBGKViIV+yUH+vnRMR0UYHJkjbNCOwxC4lyoUxn6751IPfC1vW9X8IGv5ewHrSoPisvWOo+mPU8yLEH8R6GG4CDkGaB5GC1Usn9+Zs1hgtMEEURQoMr1JXPqWEZwq7Bbew9auhZgyffP10K73sDEI1d4SZrySFDUJ0ELWRLF8IjMEUHy5zJxG5nkHZl49WTSwcrd7xj0rChZcqgsYReGd3YdCV3VbG9IJrG9c7qGgIwFGTwdZbKTsfoWGdJo53RPqNkuOkTrN1erBQ8StnNXHJa5YhW+r3ngrxaRhgDUY0ctPG+Z5jTAXh2rMuehWyRKa1OSKYWcwYwd1cuf9gW42v0DsDgKge6RllvcDP8oPlFdJjRn/TOJvuG9rztZCN3vfTBpBKeLVW44RNGSo83sTLj3bJIF6qgVtTY5cOjKupXQQd5fGf3iNE3cCRTYAGYXj33239x7D7HfuSZAf8x2GbyD1VLBwh8iabLxX44bL6WN74DfU
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: cesi-ci-cd-dev
    type: kubernetes.io/dockerconfigjson
