---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: collectorshop-jwt
  namespace: cesi-ci-cd-dev
spec:
  encryptedData:
    Jwt__Key: AgAUoRcMG4orx9VGDHvdZErGqxwOYzwcnRGfrJr/ZqaC6cWxhvMtH/YxNGcw/GNbw4qFkDLTzYQE+GGSy/LaL0dHBfT109hyLMNdktWmNBR+2ORmrgZRXUBCcedc0Gjati6mRAusAhjOPpb16syKtR0rS5KnCGpmyJoz5CX7exsyExWNxfLE30kb80MeGK83BKGwpn/zlZ+TKWE1+xHhJeQ3+gOLZXf2HY5Aycu0ZzGT20fRjJlbKkx7jDA8nG9cUzjpE+e3fqMHcNNOJNIFeWDt0NApaxY1FLMluRxvJNMAXyJ3rS+3Hwkf5T9bLPf2mI0m4Bf1JWLyIdFKAWYsMOH0kSzGCJb3wNQKOXtvaNU/R87XB1+k1nWAqOUEbvvBeL0IwWWrP56Fe+Y30w6uul4IZJujGfJCoYgNiFR/FrDGCi6vVclxbOTeIrJQPoLsYauPK8P3UICLgKye2Emqc9IEOT2VCN+h2DycayR5KYL4VoQ3WLxeiCDpjjaUdjQdZN17VS3l9kyUmDAeUjuz0/wVCJiyd69NoTRTfHSm6Cuv28rypOTji/njKJ3ebOZGy9Z7A2MDhM0W9EonIyqe5VL6myB7wQa3y95KQSi//9ZkZnsHodixgGIRDbtWZRyvqMoX0Z2zSGyWLblhYQgo/2BqVkLPJ4sn4Bebz9vC0Z69JsDUYSeoOitcs9hhe+gkrl3N+542H2Yjh9UEoLH0p/nqWD+/EEJ65WigNoAEUISTzHyjFjUn9DnaNJYKHNQbiZHG8b5zi/0CAn/rHwHy63Ca
  template:
    metadata:
      name: collectorshop-jwt
      namespace: cesi-ci-cd-dev
