resources:
- ../../base
- namespace.yaml
- ingress.yaml
- ghcr-sealed-secret.yaml

namespace: cesi-ci-cd-dev

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: ENV
          value: dev
  target:
    kind: Deployment
    name: myapp

images:
- name: ghcr.io/OWNER/REPO
  newName: ghcr.io/julienforestier/collector-shop
  newTag: 937ce04
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
