apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - ghcr-sealed-secret.yaml
  - configmap.yaml

namespace: cesi-ci-cd-dev

patches:
  - target:
      kind: Deployment
      name: myapp
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

images:
  - name: ghcr.io/OWNER/REPO
    newName: ghcr.io/julienforestier/collector-shop
    newTag: 937ce04
