apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoianVsaWVuRm9yZXN0aWVyIiwicGFzc3dvcmQiOiJnaHBfUlVpbUFmZDd1c3pxWlNqTXJra1dFZnJPaWNFQTlPMVY3M1NlIiwiZW1haWwiOiJmb3Jlc3RpZXJqdWxpZW4zQGdtYWlsLmNvbSIsImF1dGgiOiJhblZzYVdWdVJtOXlaWE4wYVdWeU9tZG9jRjlTVldsdFFXWmtOM1Z6ZW5GYVUycE5jbXRyVjBWbWNrOXBZMFZCT1U4eFZqY3pVMlU9In19fQ==
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: cesi-ci-cd-dev
type: kubernetes.io/dockerconfigjson
