---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: collectorshop-bff
  namespace: cesi-ci-cd-prod
spec:
  encryptedData:
    Bff__ClientSecret: AgCWabrpOVmU0KBtVNmS731TeuSbVr6NqB6K+zXYbNrM+4tSeGZVEIy4Y8snhL91OrG8upOO7LuS3Kupg+KYNFqDfp+rzkxVfHJKJTDsdPAAtqjXZGORdptiWYSaBSrwUnKwFfUHlGI51u3Sxw/hrkIyW7EZXJjs8P+qNH+mNeP57ouvrW4bY6Lhh1idcZT4ch82bCcuL+IO+OTHyjcfNQzDQ18jd9OPrnNeFQYxyIE5AH6lHFn8SUsRvIzD6kKDyHNf4rINTvnX0JTgKS+Gg2flEwiuRT+9RrEoY4ZQ3AVcP/6NOt222W8EQ4MIQseKUwNh7X8mnFTp0fdxYqtZMx9DBLqhQEBxK+EH6VfOFugbdiTTKwhO444WtAT6hYZhyQfqujPGqdxdgwtlw8KoOlDlTdi+T5qSJsMUt7bpow/U1vpSdqgJbVzR0n2R/SHnD4OtHktZ5evuOdqCfvPSJftyMsOkX2NwpyNDaRPh9MpDwoLhCkJ2C/8baO68bMCF3lqc4UIAOGwNPsAXGcBQ7qn0sU1rUOPlMY1sDlVu2bJfwUbsf9YJ9kNmSS5xQ60TxTJbWvGN1qc9G942Yc/aMnKsB1N41k6nnYpLMz1LW+Q6bUmMs9F74xCBsH1xkwlkj0vTJxuvP2OWWYrt+ihIJmuM18q5ofTWwTnXqj6NnIruIEWbRLjY7M2rZ8wFXQGcOAbjNfvUSWPlVpnMc1U97MDdcdKQsOTwA2uV5TydSndFXXJasUN0yf2AnVvtjA==
  template:
    metadata:
      name: collectorshop-bff
      namespace: cesi-ci-cd-prod
