apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
data:
  ENV: prod
  ASPNETCORE_ENVIRONMENT: Production
  Bff__Origin: "https://julienforestier.pro"
  IdentityServer__IssuerUri: "https://julienforestier.pro"
