apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: cesi-ci-cd-prod
spec:
  encryptedData:
    .dockerconfigjson: AgDH5Z3/orM6x4csiQ9d4x+k7R4Mz+8Hb9Pc5pLv/LmvBMCdLREJic+2sOSO3A6U7kCx3+ZrIbyd53T+SfN1QJmxZ9qr7BcAIyuQFMwtPQh4NuyABIU+LDWgBFTJ+CdOa3SX/RJhjvseMhKFpiELqM2ZXHD5Y1s2gFufHfDIbqnB7ZHG+88hMKlmelwtGn0+O1wX35dBkWIgGk/DaBEXqyW9XirY5bmGg86b+EXLvieoO06Kb46Djb17PLucDURR+8EoBq39kOLthn5E5rNmFx0PXU1cP9mRfXen6aoANRP2uYOXYrBQa9TqtUiHddQ1BoVALPc7H2ERzzmBkWMIklbzm17Eavwq4QmO4c6bmRoa2FUURYcoJNOJbpYLx9FCbN5BqnnAhgmqJM1rB7XVXaPGQkF4xUZ/zJmd6vBGOcu2/7PP6Y2znlzY/namJzeGSNvarCTWIxGkUwVAZ/47WeZ0wAHo3B9LdVSbCgqKDgtL/inMgV/DM6d1DWUpCBJhRJCW1UqoskmQrOZR9nWRt7IblI2/+PLkMO6liD07jbB1F3seYkB67881s0ZOvD7OyP6h3+2PRUjt4atSViogN1tevEBkdVluv0KWOL5sEOv2AEX6L6q+P4MFbL6NxH8Pr++UpYO3RurOK91RpLHOB8MdLCPTob2NJqCxWcxWdSJ/2GLwabr+grkB9Xx2Xc3cd5IIc1kiSAIU9jtOARzKpJnquGCwSfCKCcVZhjKlOxqHen6SJfmEHKTIGbwODCxVEe2Hfds9k7jewmRxCUv4s3fbhHNvhdd41PWK2Trr/bFvM6fIGpeF1Dvy9W3GCSYZw74jQJ+ljUxAq8si5xV3GARjTPZ0mYzWB6YOZf/K6+wt/0vNo5qz8yPHikRri9CQyDi+SHQ76tYzPmLhVy/GXfWpT899Acc6pqzSQF9nZBb6cllKRNAG6esI8xvO3J7cNWg1Z69SJ966arU4SRjpLhWpVz0N11c4NlI8IbWft9lIJcVpIqag
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: cesi-ci-cd-prod
    type: kubernetes.io/dockerconfigjson
