apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: cesi-ci-cd-prod-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - julienforestier.pro
      secretName: myapp-tls
  rules:
    - host: "julienforestier.pro"  
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: apiservice
                port:
                  number: 80
          - path: /bff
            pathType: Prefix
            backend:
              service:
                name: apiservice
                port:
                  number: 80
          - path: /connect
            pathType: Prefix
            backend:
              service:
                name: identityservice
                port:
                  number: 80
          - path: /.well-known
            pathType: Prefix
            backend:
              service:
                name: identityservice
                port:
                  number: 80
          - path: /account
            pathType: Prefix
            backend:
              service:
                name: identityservice
                port:
                  number: 80
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: identityservice
                port:
                  number: 80
          - path: /register
            pathType: Prefix
            backend:
              service:
                name: identityservice
                port:
                  number: 80
          - path: /identity-assets
            pathType: Prefix
            backend:
              service:
                name: identityservice
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myapp
                port:
                  number: 80