---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: collectorshop-jwt
  namespace: cesi-ci-cd-prod
spec:
  encryptedData:
    Jwt__Key: AgAVcaI3y0CR9AeNQAULwsW2s1vkayekYQ/ZiEuj88kfzEMDSiSdY8TJ/yCt2XDmd9XmqXfOfIJvZU6ff16BDHw6gfxY+OVQ9XCcHhOLTx9yL1ayiANwmt5BvnXJrIKYKj+2iiYF4gakU1rvQ1c8t3XZBICCTuoiEsks2jGBEQvHjDTcggfLmcjBvp8fnH5HFjGWRWN6jrvuQX+wGjqYsQIVRjnwqKKU3EcTbUl6s5N23Ph/+riIfucO9+fkNJHWMZ7QX86gHJ29A1dCzK2bI2/ucczPxHxP/3s1El0VX5uPB8+SsVzvjoqMJ2oG076OnDM1TfLevnKkocvaSHW0idGjqBPeEEdgAPU69M5tmQBboFgDjaHn4R85GrXZl8OxPAeaM9B2j92IJOLj3ltzBlHykEKLG19jwxR7NEmd29eiRFuVu9HXqV3Q29ZPAxOW9qOl0xf1y1MTxfLYb88qEWUuUCX+tFYg3lsjrokcpGdSGfCtNnFg06slH9MIHZooztx9m/79eQXuWmgodMflZPVwK67Z4oDYZBPrRD8O7tcIWiroU28UBwrw7a7aqHgO7Z9QS5RBSIM3mODZX13mTZrV/rJCwhTajyaGcmUFG4xbHETp88YVw3LVOg4nBN9liPLHgw+PxYnxv/hp31s1Wx1yg34SCRfxtkanfR8wV9fpTr5ScRFx/6RAtqLH2qx6fjNbRZJGNb/ikgcPWZmArOiYMGUm4p+0dr9b5GN35gsvl4um+u3Ly1JvlVx89uLkWjEpvnzCT8e1cIUkZZX4UcGn
  template:
    metadata:
      name: collectorshop-jwt
      namespace: cesi-ci-cd-prod
