resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - ghcr-sealed-secret.yaml
  - configmap.yaml
  - jwt-sealed-secret.yaml

namespace: cesi-ci-cd-prod

patches:
  - target:
      kind: Deployment
      name: myapp
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Cluster
      name: collectorshop-db
    patch: |-
      - op: replace
        path: /spec/instances
        value: 2
