apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cesi-ci-cd-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/JulienForestier/CESI-CI-CD-kubernetes.git'
    targetRevision: prod
    path: overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: CESI-CI-CD-PROD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true