---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: collectorshop-bff
  namespace: cesi-ci-cd-rec
spec:
  encryptedData:
    Bff__ClientSecret: AgA/YgewLF4ngCCzBEg5/+j91v1vfFGESQRiG723WISVqNDvI+tynntwszSMhwACsTxkKetZxqByEAMvHo4u8nsI0W1s5AZPtAlkuwFhFHCDjI/ICMJVeXCbHCHzRENe18GX5JOfeSoVzZZBlfDb0v9DOh9B8DIEFpZliATnoG3a1V3ZFyEh5yAeJg484cEEAamPVasZTW761h2QBNSB/nRFLAMQbSvhZnzn/OemJJm4lPorIlf8+J1iVW0XiIV8MoyRGJL7t6L4S4Qx2okkCWoG5GGW55KZaCEKf51wohi6uz7brXyfSvTNlmCT5VzOfWCsvu9oRLfsogT9qfjRu8jHC20VSvnfngHh5sAw8GOCiVUgKnTiblR7CLZrAQjI51Xq+Mchn0xRuBj/y6Pw520XMufmvJxNcWCu73tPvTcIpg9ZGPgMtp7IM3nrGJmYBk3uttWcRVH26+XV2XcOZZbMjiIRWcsFph2KnqSJtcQReY0xUmi3+Qx6uXkNELoRuuEdG+K6DNJEtN+YTU5zu7L3I+NVnKB2Na1DZjCXYbXAah3m6OKtEOz5btJlqf6SkVgquxzcU+DeDdWUM+o5wftxeZwrGXkFcN0c8ONBh4P9AL+I7NC1R4IyApPXRHYTyWtDJLbOvXR4gozOkePS8ngwBOZbhN/fISOxBDM8SVEkfA7+pNajdKn39JXjqbfPenXB2eCfewDuKRzSliTvlGD6+OA2wv2lagBPhvu+T87Nvgj1JhrwJ0UNtkHt4A==
  template:
    metadata:
      name: collectorshop-bff
      namespace: cesi-ci-cd-rec
