apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
data:
  ENV: recette
  ASPNETCORE_ENVIRONMENT: Staging
  Bff__Origin: "https://rec.julienforestier.pro"
  IdentityServer__IssuerUri: "https://rec.julienforestier.pro"
