apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: cesi-ci-cd-rec
spec:
  encryptedData:
    .dockerconfigjson: AgAGegK5/MsTnbo/1e9lHU6PbGC+3G0KrYQFlx6QgcZV+XOiN7wg3aIBRyWzAa0vh/2N3W/XOvRVJsmT0Q4S7iuEgKzrraggs4n8680fq8dz++bTuft1V8InGqovF5X4TPYjnU2Q+lLMwyP8J79tkYDlwvOx26IPSfxLfzbeBakl9NNzwJ+jSKbM4+BEZ4pCgXCFwSFAqGSp/YUIRx8Bo/ORvJxlUIUsYtQjC+npi46n2SbnsZjzlJ3yVhOI1yft60M0I1JBGTqIiAZi30H3bA4kgh2XvcWMrEYQPtFC4A6QxB6oFQIeb21rWm4lqimzVBAvTrdihjSEXOjvy7me6oxbE1ZPOIPvHb1kgPLOZlaL0h31VR29s3f0605bhVbZjuZfvHh7HDBHDajuGtGxC04Ld/gh8AiDM9JloJ56GE0cyrphQluthKODzEdRRw0kGUEv/hUcf7jrE2Vd5jw8lC22+lqeTqAatvK1eKi7DtDWYbeIT3oSSfpMsOcPpIj1PK26D9pZnZivk4zjDGywrFXy0jFUWvrQyFZAqtUco/VqIA/3bM0Vt6EtUuMbUadLvIWlfTHYBUarca5o4s3t4ZtFrnT8xtEvuIjnBXF3H3KSkQjhYTdcSpM/xPSs+uYV3TsFYHatUGAXqhbNBrijxW4UIv899m4AZV0Xx9xN4Ae8YcFJp/SUIPK7e0kF6Ed7i7KbQjc9MqQVET0euWelnKPbQSgf+xDWCuQkPAXfe6wEkKmP3xMUTogErzrCRYb5YfkJWUXMlLgBYrOSFmcrUMz9NOyom7VNDnEllwvHkNsvzY5VVU6J4JOnEvp2U4Nz9kL78JcAXDI7/8R+AANkyzaGYtuCzcXfMd6HCoci5l/EIc/xyqVscwPX7F921lz/o3VMc/f0yhIXj8kPOSa6c4a0fWBQGfk4K15363HlZhy0vz8SPv9gldNCLyR/N3Y55UJVYNJUyTfdsUviIqyPcMeg18CDuj8F0Qe+lui8YxUlXMhEZOI6
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: cesi-ci-cd-rec
    type: kubernetes.io/dockerconfigjson
