---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: collectorshop-jwt
  namespace: cesi-ci-cd-rec
spec:
  encryptedData:
    Jwt__Key: AgAiRX91g8M9WJz0H2srEkaYih9CdjevPP04rDm4gLaSYBRTESye5lbNUor5tX874E8a5gqiO2hniZCEk57z5jNiC50JyZ2G81Fk1ETlNtg8dsH2bQE6cG7z/0e+qKhI3MkenkYBC7tdSgzgrlyOz725OHgQhwUA4iinSQj+bvtGLS/Yh02G0u62jsz75O7eRoSuGgFRaTYVPud8QCzz/fNM7C6JJ7acQN0Q5WXe4e9J9nKOu5WVTtW3jhdbnsTLhfPYbtY9xDaCn4HRdO9n7r3BASLTuyLXpTGLF3AfISgXPxRzANWveqJDdOt2Mez/igtywzu/i0GVatFQAcXopw93+nTlCJj4vLwthoo5SAlak6raH7Oy7TWc8+tqE8wtD+OFEszFZm5bv48SYU8JAcnzU3upADWhOkBXlJCoefjHQVwHXG33JxC1er+fAmkSpEAgScR6vX3g+cclKXhcZLBA7UHhMNC28w1TK9jjtUZgVXaiaYnBJD/wZijJyiCGCSkQUpgeXLqYUXn2WHXGiFZhJshtnTyYjslJpGmv1+TDh2liFSEOES1EGENEg+YyCWh4V1LYg6IJfYZI6l8PFy0i9AbRnK78mH8sai85lAf3TZKBz1hK0rWt/Jid64DbiDXO6ebCaucpDjBt/VI4JtvQzqQuUEGerqJaGhfxNnihfbvaTGoGosqUen1fowQAiQB4Nw5rywuuwcE1cfzO+bbP2XTk0nt50yOw3onsY3+z51Lt0TkP8hjct16rNERj0azy38hrYt4hUEM7F3q1wM84
  template:
    metadata:
      name: collectorshop-jwt
      namespace: cesi-ci-cd-rec
